import { Inter } from 'next/font/google'
import Nav from './components/Nav'
import './globals.css'
import ThemeContextProvider from './context/useThemeContext'
import { Providers } from './providers/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeContextProvider>
          <Providers>
            <Nav />
            {children}
          </Providers>
        </ThemeContextProvider>
      </body>
    </html>
  )
}
